---
- name: Setup DuckDns
  ansible.builtin.import_tasks: duckdns.yml

- name: Ensure WireGuard and PiVPN directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - /home/{{ ansible_user }}/wireguard-backup

# 1. Transfer Backup Files
- name: Transfer WireGuard backup
  ansible.builtin.copy:
    src: "{{ ansible_files_path }}/backups/vpn/wireguard-backup.tar.gz"
    dest: /home/{{ ansible_user }}/wireguard-backup/wireguard-backup.tar.gz
    mode: '0644'

- name: Get file details
  ansible.builtin.stat:
    path: /etc/wireguard/configs/clients.txt
  register: file_info

- name: Stop PiVPN (WireGuard)
  ansible.builtin.service:
    name: wg-quick@wg0
    state: stopped
  when: file_info.stat.size == 0

- name: Extract the backup archive if /etc/wireguard is missing
  ansible.builtin.unarchive:
    src: /home/{{ ansible_user }}/wireguard-backup/wireguard-backup.tar.gz
    dest: /etc
    remote_src: true
  when: file_info.stat.size == 0

- name: Start PiVPN (WireGuard)
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
  when: file_info.stat.size == 0
