---
# Setup Home Assistant
- name: Ensure Home Assistant config directory exists
  ansible.builtin.file:
    path: /var/homeassistant
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Home Assistant Docker container
  community.docker.docker_container:
    name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant
    state: started
    restart_policy: always
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "/var/homeassistant:/config"

# Create backup directory
- name: Ensure Home Assistant backups directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/backups/homeassistant"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

# Setup nightly updates
- name: Copy Home Assistant update script
  ansible.builtin.copy:
    src: files/home-assistant.sh
    dest: /usr/local/bin/home-assistant.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure update script is executable
  ansible.builtin.file:
    path: /usr/local/bin/home-assistant.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: file

- name: Schedule home assistant update via cron
  ansible.builtin.cron:
    name: "Update home assitant container"
    minute: "0"
    hour: "3"
    job: "/bin/bash /usr/local/bin/home-assistant.sh"
    user: "{{ ansible_user }}"
    state: present
  diff: no