# Ensure Docker
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure the Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user | default('pi') }}"
    groups: docker
    append: yes
  when: ansible_user is defined

# Setup Portainer
- name: Ensure Portainer volume exists
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Deploy Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

# Setup container folders
- name: Ensure Home Assistant backup directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/backups/homeassistant"
    state: directory
    mode: '0755'

- name: Ensure /var/llm-models directory exists
  ansible.builtin.file:
    path: /var/llm-models
    state: directory
    mode: '0755'
    owner: root
    group: root