---
# Setup Portainer
- name: Ensure Portainer volume exists
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Deploy Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

# Setup nightly updates
- name: Copy Portainer update script
  ansible.builtin.copy:
    src: files/portainer.sh
    dest: /usr/local/bin/portainer.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure update script is executable
  ansible.builtin.file:
    path: /usr/local/bin/portainer.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: file

- name: Schedule portainer update via cron
  ansible.builtin.cron:
    name: "Update portainer Docker container"
    minute: "0"
    hour: "3"
    job: "/bin/bash /usr/local/bin/portainer.sh"
    user: "{{ ansible_user }}"
    state: present
  diff: no