---
- name: Ensure cgroups are configured correctly in cmdline.txt.
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  register: cmdline_result
  when: ansible_distribution == 'Debian'

- name: Reboot the machine
  ansible.builtin.reboot:
    msg: "Rebooting as part of Ansible playbook"
    reboot_timeout: 300
    test_command: uptime
  when: cmdline_result is changed