---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set default firewall rules
  command: "{{ item }}"
  loop:
    - ufw default deny incoming
    - ufw default allow outgoing

- name: Allow essential services
  command: "{{ item }}"
  loop:
    - ufw allow 22/tcp
    - ufw allow 53/tcp
    - ufw allow 53/udp
    - ufw allow 51820/udp
    - ufw allow 80/tcp
    - ufw allow 443/tcp
    - ufw allow 8123/tcp
    - ufw allow 8083/tcp
    - ufw allow 6123/tcp
    - ufw allow 6052/tcp

- name: Enable UFW with automatic confirmation
  expect:
    command: ufw enable
    responses:
      'Command may disrupt existing ssh connections. Proceed with operation (y|n)?': 'y'
    timeout: 30