---
- name: Ensure /var/code-space directory exists
  ansible.builtin.file:
    path: /var/code-space
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  
- name: Pull Code Space Docker image
  community.docker.docker_image:
    name: ghcr.io/cole-titze/containers/code-space:latest
    source: pull

- name: Run Code Space Docker container
  community.docker.docker_container:
    name: code-space
    image: ghcr.io/cole-titze/containers/code-space:latest
    state: started
    restart_policy: always
    volumes:
      - /var/code-space:/code-space
    ports:
      - "8090:8090"
    detach: true
    env:
      PASSWORD: "{{ code_space_password }}"

# Setup nightly updates
- name: Copy code space update script
  ansible.builtin.copy:
    src: files/containers/code-space.sh
    dest: /usr/local/bin/code-space.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure update script is executable
  ansible.builtin.file:
    path: /usr/local/bin/code-space.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: file

- name: Schedule code space update via cron
  ansible.builtin.cron:
    name: "Update code space container"
    minute: "0"
    hour: "3"
    job: "/bin/bash /usr/local/bin/code-space.sh"
    user: "{{ ansible_user }}"
    state: present
  diff: no