---
- name: Ensure /var/code-space directory exists
  ansible.builtin.file:
    path: /var/code-space
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  
- name: Pull Code Space Docker image
  community.docker.docker_image:
    name: ghcr.io/cole-titze/containers/code-space:latest
    source: pull

- name: Run Code Space Docker container behind Traefik
  community.docker.docker_container:
    name: code-space
    image: ghcr.io/cole-titze/containers/code-space:latest
    state: started
    restart_policy: always
    volumes:
      - /var/code-space:/home/coder
    labels:
      traefik.enable: "true"
      traefik.http.routers.code-space.rule: "Host(`code.deploypi`)"
      traefik.http.routers.code-space.entrypoints: "websecure"
      traefik.http.routers.code-space.tls: "true"
      traefik.http.services.code-space.loadbalancer.server.port: "8090"
    env:
      PASSWORD: "{{ code_space_password }}"
    detach: true
    networks:
      - name: traefik

# Setup nightly updates
- name: Template code space update script
  ansible.builtin.template:
    src: files/containers/code-space.sh.j2
    dest: /usr/local/bin/code-space.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure update script is executable
  ansible.builtin.file:
    path: /usr/local/bin/code-space.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: file

- name: Schedule code space update via cron
  ansible.builtin.cron:
    name: "Update code space container"
    minute: "0"
    hour: "3"
    job: "/bin/bash /usr/local/bin/code-space.sh"
    user: "{{ ansible_user }}"
    state: present
  diff: no